# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.adj_fun <- function(response, explanatory_complete, explanatory_proportional, distribution, categories_order, dataframe) {
    .Call(`_pack_adj_fun`, response, explanatory_complete, explanatory_proportional, distribution, categories_order, dataframe)
}

GLMcum <- function(response, explanatory_complete, explanatory_proportional, distribution, categories_order, dataframe, beta_t, beta_init) {
    .Call(`_pack_GLMcum`, response, explanatory_complete, explanatory_proportional, distribution, categories_order, dataframe, beta_t, beta_init)
}

GLMref <- function(response, explanatory_complete, explanatory_proportional, distribution, categories_order, dataframe, freedom_degrees = 2.0) {
    .Call(`_pack_GLMref`, response, explanatory_complete, explanatory_proportional, distribution, categories_order, dataframe, freedom_degrees)
}

GLMseq <- function(response, explanatory_complete, explanatory_proportional, distribution, categories_order, dataframe) {
    .Call(`_pack_GLMseq`, response, explanatory_complete, explanatory_proportional, distribution, categories_order, dataframe)
}

